name: gh-pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2.0.1
